#   ___  __    ____    __    _  _   ___  ___
#  / __)(  )  ( ___)  /__\  ( \( ) / __)/ __)
# ( (__  )(__  )__)  /(__)\  )  (  \__ \\__ \
#  \___)(____)(____)(__)(__)(_)\_) (___/(___/
# Configuration file. Made with ❤ by frafol.
# For support: discord.io/futuredevelopment


settings:

  # Name of the Hack Control server and the fallback server.
  server_name: "Control"
  fallback_server_name: "Hub"

  # This will check if you have been properly connected to the control server,
  # and if not, it will exit the control. If you encounter an error in the console
  # telling you that the server may be offline or crashed,
  # but you are sure that this is active, disable this feature.
  check_for_problems: true

  update_check: true
  stats: true

permissions:

  # You can personalize permissions.
  control: screenshare.control
  bypass: screenshare.bypass
  reload: screenshare.reload

# Enjoy.
