name: CleanScreenShare
version: '${project.version}'
main: it.frafol.cleanss.bukkit.CleanSS
authors: [ frafol ]
api-version: 1.13
folia-supported: true
description: "Addition for CleanSS (Bungee/Velocity)"
commands:
  spawn:
    description: "Teleport to the spawn"
    usage: "/spawn"
  setadminspawn:
    description: "Set the admin spawn"
    usage: "/setadminspawn"
  setsuspectspawn:
    description: "Set the suspect spawn"
    usage: "/setsuspectspawn"
  setotherspawn:
    description: "Set the other spawn"
    usage: "/setotherspawn"
softdepend:
  - PlaceholderAPI
  - LuckPerms