options:

  # Bypass command prevent.
  staff_permission: "screenshare.control"

  invincible: true

  teleport_to_spawn_on_join: true
  change_gamemode_on_join: true

  prevent:
    void: true
    hunger: true
    chat: true
    commands: true