#   ___  __    ____    __    _  _   ___  ___
#  / __)(  )  ( ___)  /__\  ( \( ) / __)/ __)
# ( (__  )(__  )__)  /(__)\  )  (  \__ \\__ \
#  \___)(____)(____)(__)(__)(_)\_) (___/(___/
# Settings file. Made with ❤ by frafol.
# For support: https://discord.com/invite/sTSwaGBCdC

options:

  update_check: true
  auto_update: true

  # Hook with PlaceholderAPI.
  placeholderapi_hook: true

  # Bypass command and move prevention.
  staff_permission: "screenshare.control"
  admin_permission: "screenshare.admin"

  # Makes all online players invincible.
  invincible: true

  # Teleports to Spawn at Join.
  teleport_to_spawn_on_join: true

  # Change player's gamemode on player's join.
  # Supported values: survival, creative, adventure, spectator.
  # If you want to disable this feature, set this value to "none".
  change_gamemode_on_join: "adventure"


  # If you want to disable this feature, set this value to "none".
  # If you want to remove completely the message, set this value to "disabled".
  custom_join_message: "&7[&a+&7] &e%player%"
  custom_leave_message: "&7[&c-&7] &e%player%"

  # Action preventions.
  prevent:

    # Prevent player actions.
    player:
      block_place: true
      block_break: true
      move: false
      pvp: true
      void: true
      hunger: true
      chat: true

    # Prevent world changes.
    world:
      weather_change: true
      daylight_cycle: true
      mob_spawning: true

  messages:

    # Messages sent to the player when he sets a player spawn in the server.
    spawn_set: "&aSpawn has been set in your position."

    # Prefixes of the players, you can use it in all plugins that support PlaceholderAPI.
    # Placeholders: %screenshare_prefix%
    staff_prefix: "&7[&cStaff&7] &r"
    suspect_prefix: "&7[&eSuspicious&7] &r"

  scoreboard:

    # The time in ticks after which the scoreboard will be updated.
    # Lower values may cause performance issues.
    update_task: 40

    # NOTE: In this section, you can use ALL placeholderapi placeholders, if you have it installed.
    staff_board:
      enabled: true

      # Title of the scoreboard.
      title: "&c&lSCREENSHARE"

      # Lines of the scoreboard.
      lines:
        - "&c"
        - "&7Suspect: &e%screenshare_suspicious%"
        - "&7Time: &e%screenshare_time%"
        - "&f"
        - "&emc.yourserver.com"

    suspect_board:
      enabled: true

      # Title of the scoreboard.
      title: "&c&lSCREENSHARE"

      # Lines of the scoreboard.
      lines:
        - "&c"
        - "&7Staff: &c%screenshare_administrator%"
        - "&7Time: &e%screenshare_time%"
        - "&f"
        - "&emc.yourserver.com"

  tablist:

    # The time in ticks after which the tablist will be updated.
    # Lower values may cause performance issues.
    update_task: 100

    # NOTE: This wll work only if your spigot version is not legacy (1.13.2 - Latest).
    # The format of the players in the tablist.
    # PlaceholderAPI placeholders are supported.
    format: "%screenshare_prefix%%player%"

    # NOTE: In this section, you can use ALL placeholderapi placeholders, if you have it installed.
    staff_tablist:
      enabled: true

      # Header and footer of the tablist.
      header:
        - "&c&lSCREENSHARE"
        - "&f"

      footer:
        - "&f"
        - "&7Suspect: &e%screenshare_suspicious%"

    suspect_tablist:
      enabled: true

      # Header and footer of the tablist.
      header:
        - "&c&lSCREENSHARE"
        - "&f"

      footer:
        - "&f"
        - "&7Administrator: &e%screenshare_administrator%"

# Enjoy.